name: DLEnv
channels:
    - conda-forge
    - defaults
    - anaconda
    - conda-forge/label/broken
dependencies:
    - python
    - matplotlib
    - xarray
    - pandas
    - scikit-learn
    - cartopy
    - pygrib 
    - pip
        - tensorflow
        - netcdf4
        - git+https://github.com/yingkaisha/keras-unet-collection.git
